trigger:
  branches:
    include:
    - master
variables:
- name: buildConfiguration
  value: Release
stages:
- stage: __default
  jobs:
  - job: Job
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: UseDotNet@2
      displayName: Install .NET Core SDK
      inputs:
        packageType: sdk
        version: 3.1.x
    - task: CmdLine@2
      displayName: dotnet build $(buildConfiguration)
      inputs:
        script: dotnet build --configuration $(buildConfiguration)
    - task: DotNetCoreCLI@2
      inputs:
        command: publish
        publishWebProjects: true
        arguments: --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: $(Build.ArtifactStagingDirectory)
        ArtifactName: drop
        publishLocation: Container

